---
title: "figures"
output: html_document
---
# Setup

```{r everyone load data, message = FALSE}
# this chunk should just work for everyone when you open the project. I copied the data into a subfolder called data within this project, but in case it doesn't work I left Noel and Kelley's load chunks below

source("setup.R")

dynamism_data <- read_csv("data/figures_data/dynamism_data.csv")
data_byyr <- read_csv("data/figures_data/data_byyr.csv") 

all_data_byyr <- read.csv("data/ALL_metrics_07022026.csv") 
```

```{r clean loaded data}
## this should work after you run the right version of data loading above

# dynamism_data <- dynamism_data[1:13,] %>% # for some reason we have duplicate rows in the csv
#   bind_rows( # also want to add back the mod rock_WA site
#     dynamism_data %>% 
#       slice(6) %>% 
#       mutate(across(
#         c(site_reach, site),
#         ~ str_replace_all(.x, "_1", "_2")
#         ))
#     ) 

data_byyr <- data_byyr %>% 
  rename(reach = site,
         site = river) %>% 
  mutate(site_reach = paste0(site,reach,ab)) %>% 
  mutate(ratio_accum_to_ch_area = accum_area/channel_area,
         piece_per_100m = (wood_pieces/channel_length)*100,
         site = factor(site),
         reach = factor(reach))

all_data_byyr <- all_data_byyr %>% 
  rename(reach = site,
         site = river) %>% 
  mutate(site_reach = paste0(site,reach))
```

```{r plot settings}
wood_colors = c("LW_Channel" = "#BEA57D", "no_LW_Channel" = "#99C5B5")#BEA57D
```

# Mean wood bar plot

```{r}

##### mean wood values by site #####
p1 <- dynamism_data %>% 
  group_by(ab) %>%
  ggplot(aes(x = name, y = avg_wood_pieces_per100m, fill = reach)) +
  geom_col(position = position_dodge2(preserve = "single")) +
  scale_fill_manual(values = wood_colors,
                    name = "Reach Type",
                    labels = c("Wood rich", "Wood poor")) +
  scale_x_discrete(guide = guide_axis(angle = 25)) +
  theme_bw()  +
  labs(y = "Mean # pieces/100 m") +
  geom_text(aes(label = ab),
            position = position_dodge2(width = 0.9),
            vjust = -0.9) +
  theme(axis.text = element_blank(),
        axis.title.x = element_blank(),
        legend.position = "none")

# Wood accumulation area normalized by channel area at each time step, averaged for each site

p2 <- dynamism_data %>% 
  group_by(ab) %>%
  ggplot(aes(x = name, y = mean_wood_accum_per_area, fill = reach)) +
  geom_col(position = position_dodge2(preserve = "single")) +
  scale_fill_manual(values = wood_colors,
                    name = "Reach Type",
                    labels = c("Wood rich", "Wood poor")) +
  theme(legend.position = "none") +
  scale_x_discrete(guide = guide_axis(angle = 25)) +
  theme_bw()  +
  labs(x = "Site",
       y = "Mean wood accumulation area:channel area") +
  geom_text(aes(label = ab),
            position = position_dodge2(width = 0.9),
            vjust = -0.9)

mean_wood_by_site <- (p1 / p2)

ggsave(mean_wood_by_site,
       filename = "output/mean_wood_by_site.jpg",
       height = 6.5,
       width = 7,
       units = "in",
       dpi = 300)

```

# Metrics X time

## Wood x time facet wrap

```{r}
acc_over_time <- data_byyr %>%
  group_by(ab) %>%
  ggplot(aes(x = year, y = ratio_accum_to_ch_area, color = reach)) +
  geom_point(size = 2) +
  geom_line(aes(group = site_reach)) +
  facet_wrap(~name) +
  scale_color_manual(values = wood_colors,
          name = "Reach Type",
          labels = c("Wood rich", "Wood poor")) +
  labs(x = "Year",
       y = "Wood accumulation area (m)/Channel area (m)") + 

    theme_bw() +
  geom_text(
    data = data_byyr %>% 
      slice_min(order_by = year, n = 1, by = ab), # first point
    aes(label = ab),
    hjust = 0,        
    nudge_x = -2,     
    show.legend = FALSE,
    color = "black") +
  theme(legend.position = "inside",
        legend.position.inside = c(0.1,0.9),
        legend.background = element_rect(color = "black", linewidth = 0.25))

ggsave(acc_over_time,
       filename = "output/acc_over_time_facet.jpg",
       height = 6,
       width = 7.5,
       units = "in",
       dpi = 300)
```

## Ch metrics x time facet wrap

```{r}
# Complexity
complexity_over_time <- data_byyr %>%
  group_by(ab) %>%
  ggplot(aes(x = year, y = complexity, color = reach)) +
  geom_point(size = 2) +
  geom_line(aes(group = site_reach)) +
  facet_wrap(~name,
             nrow = 1) + # Remove if want one plot per metric
  scale_color_manual(values = wood_colors,
          name = "Reach type",
          labels = c("Wood rich", "Wood poor")) +
  labs(y = "Complexity (m/m)") + 
    theme_bw() +
  geom_text(
    data = data_byyr %>% 
      slice_min(order_by = year, n = 1, by = ab), # first point
    aes(label = ab),
    hjust = 0,        
    nudge_x = -2,     
    show.legend = FALSE,
    color = "black")  +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        legend.position = "inside",
        legend.position.inside = c(0.06,0.25),
        legend.background = element_rect(color = "black", linewidth = 0.25))

complexity_over_time

# ggsave(complexity_over_time,
#        filename = "output/complexity_over_time_facet.jpg",
#        height = 6,
#        width = 7.5,
#        units = "in",
#        dpi = 300)

# Sin x time facet wrap
sinuosity_over_time <- data_byyr %>%
  group_by(ab) %>%
  ggplot(aes(x = year, y = sinuosity, color = reach)) +
  geom_point(size = 2) +
  geom_line(aes(group = site_reach)) +
  facet_wrap(~name,
             nrow = 1) +# Remove if want one plot per metric
  scale_color_manual(values = wood_colors,
          name = "Reach type",
          labels = c("Wood rich", "Wood poor")) +
  labs(y = "Sinuosity") + 
    theme_bw() +
  geom_text(
    data = data_byyr %>% 
      slice_min(order_by = year, n = 1, by = ab), # first point
    aes(label = ab),
    hjust = 0,        
    nudge_x = -2,     
    show.legend = FALSE,
    color = "black") +
    theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        strip.background = element_blank(),
        strip.text = element_blank(),
        legend.position = "none")

# ggsave(sinuosity_over_time,
#        filename = "output/sinuosity_over_time_facet.jpg",
#        height = 6,
#        width = 7.5,
#        units = "in",
#        dpi = 300)


# Channel area

# Need some way to show net change over time... because its a year-to year thing..
# Could show channel area normalized by channel length each year?

ch_area_over_time <- data_byyr %>%
  mutate(ch_area_norm = channel_area/channel_length) %>%
  group_by(ab) %>%
  ggplot(aes(x = year, y = channel_area, color = reach)) +
  geom_point(size = 2) +
  geom_line(aes(group = site_reach)) +
  facet_wrap(~name,
             nrow = 1) + # Remove if want one plot per metric
  scale_color_manual(values = wood_colors,
          name = "Reach type",
          labels = c("Wood rich", "Wood poor")) +
  labs(x = "Year",
       y = expression(paste("Channel area (", m^{2}, ")"))) + 
  theme(legend.position = "right") +
    theme_bw() +
  geom_text(
    data = data_byyr %>% 
      slice_min(order_by = year, n = 1, by = ab), # first point
    aes(label = ab),
    hjust = 0,        
    nudge_x = -2,     
    show.legend = FALSE,
    color = "black") +
  theme(legend.position = "none",
        strip.background = element_blank(),
        strip.text = element_blank())

# ggsave(ch_area_over_time,
#        filename = "output/ch_area_over_time_facet.jpg",
#        height = 6,
#        width = 7.5,
#        units = "in",
#        dpi = 300)

## Facet wrap grid

metric_grid <- (complexity_over_time / sinuosity_over_time / ch_area_over_time)

ggsave(metric_grid,
       filename = "output/metric_grid.jpg",
       height = 7,
       width = 12,
       units = "in",
       dpi = 300)
```


# Mega dynamism panel

```{r simple dynamism plots PART 2 MEGA PANEL}
##### Sinuosity vs both mean wood metrics #####
p1 <- dynamism_data %>%
  ggplot(aes(x = avg_wood_pieces_per100m, y = sinuosity_dynamism, color = site)) +
  geom_point(aes(shape = reach), size = 3) +
    scale_color_carto_d(palette = "Earth") +
    scale_shape_manual(
      values = c(16, 17),
      labels = c("Large Wood", "Control"),
      name = "Reach Type") +
  geom_line(aes(group = site), color = "black", alpha = 0.5) +
  theme_bw() + 
  theme(legend.position = "none") +
  labs(x = "", 
       y = "Sinuosity",
       color = "Site",
       shape = "Reach Type")

p2 <- dynamism_data %>%
  ggplot(aes(x = mean_wood_accum_per_area, y = sinuosity_dynamism, color = site)) +
  geom_point(aes(shape = reach), size = 3) +
    scale_color_carto_d(palette = "Earth") +
    scale_shape_manual(
    values = c(16, 17),
    labels = c("Large Wood", "Control"),
    name = "Reach Type") +
  geom_line(aes(group = site), color = "black", alpha = 0.5) +
  theme_bw() +
  theme(legend.position = "none") +
  labs(x = "", 
       y = "",
       color = "Site",
       shape = "Reach Type")

sinuosity <- (p1 + p2) +
  plot_annotation(title = "Sinuosity Dynamism vs. Avg Wood Metrics")
##### end 

##### Complexity vs both mean wood metrics #####
p3 <- dynamism_data %>%
  ggplot(aes(x = avg_wood_pieces_per100m, y = complexity_dynamism, color = site)) +
  geom_point(aes(shape = reach), size = 3) +
    scale_color_carto_d(palette = "Earth") +
    scale_shape_manual(
      values = c(16, 17),
      labels = c("Large Wood", "Control"),
      name = "Reach Type") +
  geom_line(aes(group = site), color = "black", alpha = 0.5) +
  theme_bw() + 
  theme(legend.position = "none") +
  labs(x = "", 
       y = "Complexity",
       color = "Site",
       shape = "Reach Type")

p4 <- dynamism_data %>%
  ggplot(aes(x = mean_wood_accum_per_area, y = complexity_dynamism, color = site)) +
  geom_point(aes(shape = reach), size = 3) +
    scale_color_carto_d(palette = "Earth") +
    scale_shape_manual(
    values = c(16, 17),
    labels = c("Large Wood", "Control"),
    name = "Reach Type") +
  geom_line(aes(group = site), color = "black", alpha = 0.5) +
  theme_bw() +
  theme(legend.position = "right") +
  labs(x = "", 
       y = "",
       color = "Site",
       shape = "Reach Type")

complexity <- (p3 + p4) +
  plot_annotation(title = "Complexity Dynamism vs. Avg Wood Metrics")
##### end

##### SDI vs both mean wood metrics #####
p5 <- dynamism_data %>%
  ggplot(aes(x = avg_wood_pieces_per100m, y = sdi_dynamism, color = site)) +
  geom_point(aes(shape = reach), size = 3) +
    scale_color_carto_d(palette = "Earth") +
    scale_shape_manual(
      values = c(16, 17),
      labels = c("Large Wood", "Control"),
      name = "Reach Type") +
  geom_line(aes(group = site), color = "black", alpha = 0.5) +
  theme_bw() + 
  theme(legend.position = "none") +
  labs(x = "", 
       y = "SDI",
       color = "Site",
       shape = "Reach Type")

p6 <- dynamism_data %>%
  ggplot(aes(x = mean_wood_accum_per_area, y = sdi_dynamism, color = site)) +
  geom_point(aes(shape = reach), size = 3) +
    scale_color_carto_d(palette = "Earth") +
    scale_shape_manual(
    values = c(16, 17),
    labels = c("Large Wood", "Control"),
    name = "Reach Type") +
  geom_line(aes(group = site), color = "black", alpha = 0.5) +
  theme_bw() +
  theme(legend.position = "none") +
  labs(x = "", 
       y = "",
       color = "Site",
       shape = "Reach Type")

sdi <- (p5 + p6) +
  plot_annotation(title = "SDI Dynamism vs. Avg Wood Metrics")
##### end

##### Net change vs both mean wood metrics #####
p7 <- dynamism_data %>%
  ggplot(aes(x = avg_wood_pieces_per100m, y = net_change_dynamism, color = site)) +
  geom_point(aes(shape = reach), size = 3) +
    scale_color_carto_d(palette = "Earth") +
    scale_shape_manual(
      values = c(16, 17),
      labels = c("Large Wood", "Control"),
      name = "Reach Type") +
  geom_line(aes(group = site), color = "black", alpha = 0.5) +
  theme_bw() + 
  theme(legend.position = "none") +
  labs(x = "Avg. Wood Pieces per 100m", 
       y = "Net Change",
       color = "Site",
       shape = "Reach Type")

p8 <- dynamism_data %>%
  ggplot(aes(x = mean_wood_accum_per_area, y = net_change_dynamism, color = site)) +
  geom_point(aes(shape = reach), size = 3) +
    scale_color_carto_d(palette = "Earth") +
    scale_shape_manual(
    values = c(16, 17),
    labels = c("Large Wood", "Control"),
    name = "Reach Type") +
  geom_line(aes(group = site), color = "black", alpha = 0.5) +
  theme_bw() +
  theme(legend.position = "none") +
  labs(x = "Avg. Wood Acculumations per Area", 
       y = "",
       color = "Site",
       shape = "Reach Type")

netdyno <- (p7 + p8) +
  plot_annotation(title = "Net Change vs. Avg Wood Metrics")


# Patching together
(p1 + p2 +
 p3 + p4 +
 p5 + p6 +
 p7 + p8) +
  plot_layout(ncol = 2) +
  plot_annotation(title = "Dynamism vs. Avg Wood Metrics")
##### end

```

#Mega z-score panel

```{r simple dynamism plots pt. 2}
library(grid)
library(rcartocolor)
library(dplyr)
library(patchwork)

## CLEANING UP
# Adjusting so all 3 metrics can be plotted on same graph

dynamism_cubed <- dynamism_data %>%
  pivot_longer(c(complexity_dynamism,sinuosity_dynamism, net_change_dynamism),
               names_to = "Metric",
               values_to = "Value") %>%
  group_by(Metric) %>%
  mutate(Value_scaled = (scale(Value))) # calculated a separate z-score for each dynamism metric
  # will show dynamism values relative to each other

# Essentially, does wood accumulation change dynamism relative to it's normal range?

# Looking at colorblind friendly color schemes
#rcartocolor::display_carto_all()
#carto_pal(7, "Earth")

# Renaming labels
dynamism_cubed <- dynamism_cubed %>%
  mutate(
    Metric = recode(
      Metric,
      complexity_dynamism = "Complexity",
      sinuosity_dynamism = "Sinuosity",
      net_change_dynamism = "Net Channel Change"
    ),
    reach = recode(
      reach,
      LW_Channel = "Wood rich",
      no_LW_Channel = "Wood poor"
    ))
    

## PLOTS

## COMBO PLOT
# Mean wood pieces across site and reach
z_pieces <- dynamism_cubed %>% ggplot(aes(
    x = avg_wood_pieces_per100m,
    y = Value_scaled,
    color = Metric
    )) +
  scale_color_manual(values = c(
  "Complexity" = "#B5B991",
  "Sinuosity" = "#70A494",
  "Net Channel Change" = "#E15759"
  ))+
 geom_point(
    aes(shape = name),
    size = 4)+
  scale_shape_manual(values = c(3,4,18,16,17,15)) +
  geom_smooth(aes(group = Metric),
              method = "lm",
              se = FALSE,
              linewidth = 1.2) +
  geom_text(
    data = dynamism_cubed,
    aes(label = ab),
    hjust = 0,        
    nudge_x = -0.005,     
    show.legend = FALSE,
    color = "black",
    size = 3,
    fontface = "bold") +
  facet_wrap(~reach) +
    facet_wrap(~reach, scales = "free_x") + # delete scale = "free_x" if you want each reach on the same scale
    labs(
    x = "Mean wood pieces (per 100m)",
    y = "Standardized dynamism (z-score)",
    color = "Dynamism Metric",
    shape = "Site")+
  xlim(0, NA) +
  theme_bw()

# Mean wood accumulation across site and reach
z_acc <- ggplot(
  dynamism_cubed,
  aes(
    x = mean_wood_accum_per_area,
    y = Value_scaled,
    color = Metric
  )
) +
  scale_color_manual(values = c(
  "Complexity" = "#B5B991",
  "Sinuosity" = "#70A494",
  "Net Channel Change" = "#E15759"
  ))+
 geom_point(
    aes(shape = name),
    size = 4)+
  scale_shape_manual(values = c(3,4,18,16,17,15)) +
  geom_smooth(aes(group = Metric),
              method = "lm",
              se = FALSE,
              linewidth = 1.2) +
  geom_text(
    aes(label = ab),
    hjust = 0,
    nudge_x = -0.005,
    show.legend = FALSE,
    color = "black",
    size = 3,
    fontface = "bold") +
    facet_wrap(~reach, scales = "free_x") + # delete scale = "free_x" if you want on the same scale
    labs(
    x = "Mean wood accumulation (per area)",
    y = "Standardized dynamism (z-score)",
    color = "Dynamism Metric",
    shape = "Site")+
  xlim(0, NA) +
  theme_bw()+
  theme(
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank()
  )


## FINAL PLOT
z_score_plot <- (z_pieces + z_acc) +
  plot_layout(guides = "collect") +
  plot_annotation(title = "Dynamism vs. Average Wood Metrics") &
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "right",
    legend.title = element_text(face = "bold"),
    legend.key.size = unit(0.4, "cm"),
    legend.spacing.x = unit(0.2, "cm"),
    legend.text = element_text(size = 9),
    legend.box.spacing = unit(0.1, "cm"),
    strip.background = element_blank(),
    strip.text = element_text(face = "bold"),
    plot.title = element_text(face = "bold", hjust = 0.5)
  ) &
  guides(
    color = guide_legend(
      title = "Dynamism Metric",
      ncol = 1
    ),
    shape = guide_legend(
      title = "Site",
      ncol = 1,
      override.aes = list(size = 3)
    )
  )

ggsave(z_score_plot,
       filename = "output/z_score_plot.jpg",
       height = 5,
       width = 9,
       units = "in",
       dpi = 300)

```


##Supplemental

### Acc & Pieces over time
```{r}


# how does standardized wood (the ratio of wood accumulation to channel area and num of pieces per 100 m of channel) change over time?

p1 <- data_byyr %>% 
  ggplot(aes(x=year, y=piece_per_100m, color = name, shape = reach)) +
  geom_point() +
  geom_line(aes(group = site_reach)) +
  theme_bw() +
  labs(x = "Year",
       y = "# of pieces/100 m") +
  geom_text(
    data = data_byyr %>% slice_max(order_by = year, n = 1, by = ab), # first point
    aes(label = ab),
    hjust = 0,        
    nudge_x = 0.2,     
    show.legend = FALSE) +
  scale_shape_discrete(
    name = "Reach type",
    labels = c("Wood rich", "Wood poor")) + # LW is alphabetically before no_LW 
  scale_color_discrete(name = "Site") +
  theme(axis.text = element_blank(),
        axis.title.x = element_blank())
# General trend of pieces increasing over time, this is likely an artifact of the imagery resolution improving. Definitely include this in the SI. This is not true for accumulations.

p2 <- data_byyr %>%
  ggplot(aes(x=year, y=ratio_accum_to_ch_area, color = name, shape = reach)) +
  geom_point() +
  geom_line(aes(group = site_reach)) +
  theme_bw() +
  labs(x = "Year",
       y = "Wood accumulation area/channel area") +
  geom_text(
    data = data_byyr %>% slice_max(order_by = year, n = 1, by = ab), # first point
    aes(label = ab),
    hjust = 0,        
    nudge_x = 0.2,     
    show.legend = FALSE) +
  theme(legend.position = "none")

wood_time_si <- (p1/p2)

ggsave(wood_time_si,
       filename = "output/wood_time_si.jpg",
       dpi = 300,
       width = 7,
       height = 6,
       units = "in")
```
